/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ulich;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
//import com.mysql.jdbc.Connection;
//import com.mysql.jdbc.PreparedStatement;
import db.DataBaseConnection;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author HP
 */
public class JPanelCaisse extends javax.swing.JPanel {

    /**
     * Creates new form JPanelCaisse
     */
    private double soldeCaisse;
    private JPanel jPanelAction;

    public JPanelCaisse() {
        initComponents();

        //jPanelAction = new JPanel();
        this.setLayout(new BorderLayout());

        this.add(jPanelSolde1, BorderLayout.NORTH);
        JPanel panelCentre = new JPanel(new GridBagLayout());
        panelCentre.setBackground(new Color(251, 252, 210));
        panelCentre.add(jPanelSolde2);
        this.add(panelCentre, BorderLayout.CENTER);

        afficherSoldeCaisse(1);
    }

    private double getSolde(Connection connection, int caisseId) {
        double soldeTotal = 0.0;
        String sql = "SELECT soldeTotal FROM caisse WHERE id = ?";

        try ( PreparedStatement ps = connection.prepareStatement(sql)) {
            ps.setInt(1, caisseId);

            try ( ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    soldeTotal = rs.getDouble("soldeTotal");
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return soldeTotal;
    }

    // Méthode pour afficher le solde dans ton JLabel
    private void afficherSoldeCaisse(int caisseId) {
        try ( Connection conn = DataBaseConnection.getConnection()) {
            double soldeTotal = getSolde(conn, caisseId);
            jLabelSolde1.setText(soldeTotal + " F CFA");
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSolde1 = new javax.swing.JPanel();
        jLabelOperation = new javax.swing.JLabel();
        jPanelSolde2 = new javax.swing.JPanel();
        jLabelSolde = new javax.swing.JLabel();
        jLabelNom = new javax.swing.JLabel();
        jComboBoxNom = new javax.swing.JComboBox<>();
        jButtonFermer = new javax.swing.JButton();
        jLabelSolde1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(528, 484));

        jPanelSolde1.setBackground(new java.awt.Color(251, 252, 210));
        jPanelSolde1.setLayout(new java.awt.GridBagLayout());

        jLabelOperation.setFont(new java.awt.Font("Vivaldi", 1, 48)); // NOI18N
        jLabelOperation.setForeground(new java.awt.Color(153, 51, 0));
        jLabelOperation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOperation.setText("Solde Caisse");
        jLabelOperation.setPreferredSize(new java.awt.Dimension(450, 89));
        jPanelSolde1.add(jLabelOperation, new java.awt.GridBagConstraints());

        jPanelSolde2.setBackground(new java.awt.Color(251, 252, 210));

        jLabelSolde.setBackground(new java.awt.Color(251, 252, 210));
        jLabelSolde.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabelSolde.setText("Solde");

        jLabelNom.setBackground(new java.awt.Color(251, 252, 210));
        jLabelNom.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabelNom.setText("Nom");

        jComboBoxNom.setBackground(new java.awt.Color(251, 252, 210));
        jComboBoxNom.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jComboBoxNom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choisir...", "Principale", "Dîme", "Quête" }));
        jComboBoxNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNomActionPerformed(evt);
            }
        });

        jButtonFermer.setBackground(new java.awt.Color(251, 252, 210));
        jButtonFermer.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jButtonFermer.setText("Fermer");
        jButtonFermer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(251, 252, 210), new java.awt.Color(251, 252, 210), new java.awt.Color(251, 252, 210), new java.awt.Color(251, 252, 210)));
        jButtonFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFermerActionPerformed(evt);
            }
        });

        jLabelSolde1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelSolde1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSolde1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanelSolde2Layout = new javax.swing.GroupLayout(jPanelSolde2);
        jPanelSolde2.setLayout(jPanelSolde2Layout);
        jPanelSolde2Layout.setHorizontalGroup(
            jPanelSolde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSolde2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanelSolde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSolde, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelSolde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxNom, 0, 213, Short.MAX_VALUE)
                    .addComponent(jLabelSolde1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43))
            .addGroup(jPanelSolde2Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jButtonFermer, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSolde2Layout.setVerticalGroup(
            jPanelSolde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSolde2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanelSolde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxNom, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(jPanelSolde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSolde, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSolde1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(jButtonFermer, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelSolde1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanelSolde2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelSolde1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelSolde2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNomActionPerformed
        // TODO add your handling code here:
        String choix = (String) jComboBoxNom.getSelectedItem();
        int caisseId = 0;

        if ("Principale".equals(choix)) {
            caisseId = 1;
        } else if ("Dîme".equals(choix)) {
            caisseId = 2;
        } else if ("Quête".equals(choix)) {
            caisseId = 3;
        }

        if (caisseId > 0) {
            afficherSoldeCaisse(caisseId);
        }
        try(Connection connection = DataBaseConnection.getConnection()){
            getSolde( connection, caisseId);
        }catch (SQLException e) {
            e.printStackTrace(); 
        }
    }//GEN-LAST:event_jComboBoxNomActionPerformed

    private void jButtonFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFermerActionPerformed
        // TODO add your handling code here:
        fermerCaisse();


    }//GEN-LAST:event_jButtonFermerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFermer;
    private javax.swing.JComboBox<String> jComboBoxNom;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelOperation;
    private javax.swing.JLabel jLabelSolde;
    private javax.swing.JLabel jLabelSolde1;
    private javax.swing.JPanel jPanelSolde1;
    private javax.swing.JPanel jPanelSolde2;
    // End of variables declaration//GEN-END:variables

    private void fermerCaisse() {
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (parentFrame != null) {
            parentFrame.getContentPane().remove(this);
            parentFrame.getContentPane().add(jPanelAction);
            parentFrame.revalidate();
            parentFrame.repaint();
        } else {
            System.out.println("Erreur : le panel n'est pas encore attaché à un JFrame !");
        }
    }

}
